--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/data/Tasks/high_speed_acquisition_system/td/sources/spi/ip/spi_ram.vhd
 -- Date	:	2023 07 28
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY spi_ram IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(15 DOWNTO 0);
	wea	: IN STD_LOGIC;
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	dob	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
	dib	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addrb	: IN STD_LOGIC_VECTOR(13 DOWNTO 0);
	web	: IN STD_LOGIC;
	ceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC
	);
END spi_ram;

ARCHITECTURE struct OF spi_ram IS

	BEGIN

	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			DATA_WIDTH_B	=> 32,
			ADDR_WIDTH_A	=> 16,
			ADDR_WIDTH_b	=> 14,
			DATA_DEPTH_A	=> 65536,
			DATA_DEPTH_B	=> 16384,
			MODE		=> "DP",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "READBEFOREWRITE",
			WRITEMODE_B	=> "READBEFOREWRITE",
			IMPLEMENT	=> "20K(FAST)",
			INIT_FILE		=> "NONE",
			CLKMODE		=> "ASYNC",
			ECC_ENCODE		=> "DISABLE",
			ECC_DECODE		=> "DISABLE",
			SSROVERCE		=> "DISABLE",
			OREGSET_A		=> "SET",
			OREGSET_B		=> "SET",
			RESETMODE_A		=> "ASYNC",
			RESETMODE_B		=> "ASYNC",
			ASYNC_RESET_RELEASE_A		=> "SYNC",
			ASYNC_RESET_RELEASE_B		=> "SYNC",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> dib,
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			ocea	=> '0',
			oceb	=> '0',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			web	=> web,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			rsta	=> '0',
			rstb	=> '0',
			doa	=> doa,
			dob	=> dob
		);

END struct;
